import { Octokit } from '@octokit/rest';
import { IssueData, ServiceResponse } from '../types';
import { GitHubError } from '../errors';

export class GitHubService {
  private octokit: Octokit;
  private owner: string;
  private repo: string;

  constructor(token: string, owner: string, repo: string) {
    this.octokit = new Octokit({
      auth: token,
      userAgent: 'AIDD-Discord-Bot/1.0',
    });
    this.owner = owner;
    this.repo = repo;
  }

  public async createIssue(data: IssueData): Promise<ServiceResponse<string>> {
    try {
      const issueTitle = `Resource Suggestion: ${data.title}`;
      const issueBody = this.generateIssueBody(data);

      const { data: issue } = await this.octokit.rest.issues.create({
        owner: this.owner,
        repo: this.repo,
        title: issueTitle,
        body: issueBody,
        labels: ['resource-suggestion', 'discord-bot'],
      });

      return {
        success: true,
        data: issue.html_url
      };
    } catch (error) {
      throw new GitHubError(
        `Failed to create issue: ${error instanceof Error ? error.message : 'Unknown error'}`,
        error
      );
    }
  }

  private generateIssueBody(data: IssueData): string {
    return `# Resource Suggestion

## 📋 Resource Details

**Title:** ${data.title}

**Description:** ${data.description}

**URL:** ${data.url}

**Submitted by:** ${data.submittedBy}

## 🤖 Automated Submission

This issue was automatically created by the AI-Driven Dev Discord Bot using the \`/save-link\` command.

## ✅ Review Checklist

- [ ] Content is appropriate for the AI-Driven Dev community
- [ ] Link is accessible and working
- [ ] Title and description are accurate
- [ ] Resource adds value to the repository
- [ ] Ready to be added to the resources collection

## 🏷️ Labels

- \`resource-suggestion\` - New resource proposed by the community
- \`discord-bot\` - Submitted via Discord bot

---

*Generated by AI-Driven Dev Discord Bot*`;
  }
}